# -*- coding: utf-8 -*-
"""Language_Translation_Tool.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Epo_rX8-wQIRF_Mg88VE-W0UqE7Uzyo

# Translation UI — Colab (Final Submission Notebook)

**What this notebook contains:**
- Safe dependency installation and version pinning.
- Azure Translator integration
- A fallback translator (Deep Translator) used automatically if Azure is not configured or returns an error.
- A robust, pure HTML+JS UI embedded in the notebook with:
  - Source & target language selectors
  - Input text area
  - Translate / Clear / Copy / Speak buttons
  - Translated text output
  - Debug box for raw responses (useful during testing)
- Clear instructions and a diagnostics cell.

**Step 1:** Install required libraries (safe pinned set)
"""

!pip uninstall -y googletrans googletrans==4.0.0-rc1 || true
!pip install -q --upgrade --force-reinstall \
  "requests==2.32.4" \
  "decorator==4.4.2" \
  "httpx>=0.28.1,<1.0.0" \
  deep-translator gTTS

# Print versions to verify clean install
import importlib
def show(pkg, imp=None):
    try:
        m = importlib.import_module(imp or pkg)
        v = getattr(m, "__version__", None) or getattr(m, "version", None) or "unknown"
        print(f"{pkg}: {v}")
    except Exception as e:
        print(f"{pkg}: not importable ({e})")

show("httpx")
show("requests")
show("deep_translator","deep_translator")
show("gtts")
show("decorator")

""" **Step 2:** Imports & config"""

import os, json, tempfile, traceback
from IPython.display import display, HTML
from deep_translator import GoogleTranslator as DeepGoogleTranslator
from gtts import gTTS

# Show whether keys are set (you can set them in the next cell)
print("AZURE_KEY set?", bool(os.environ.get("AZURE_KEY", "")))
print("AZURE_REGION set?", bool(os.environ.get("AZURE_REGION", "")))

"""## Add Azure credentials for real translation (PRIVATE)
If you want to use **Microsoft Azure Translator**, set your keys **only in this Colab session** using the cell below.

**Step 3:** Set Azure credentials for this Colab session
"""

import os
os.environ["AZURE_KEY"] = ""
os.environ["AZURE_REGION"] = ""
print("AZURE_KEY set?", bool(os.environ.get("AZURE_KEY")))
print("AZURE_REGION set?", bool(os.environ.get("AZURE_REGION")))

"""**Step 4:** Register Python callbacks callable from JS

translation.azure   -> uses Azure Translator (requires AZURE_KEY & AZURE_REGION)
translation.fallback -> uses deep-translator (no API key required)
"""

from google.colab import output as colab_output
import os, requests, traceback

def translate_with_azure_py(text, source, target):
    key = os.environ.get("AZURE_KEY", "")
    region = os.environ.get("AZURE_REGION", "")
    if not key or not region:
        return "__ERROR__:Azure key or region not set in the session environment."
    try:
        base = "https://api.cognitive.microsofttranslator.com/translate"
        params = {"api-version": "3.0", "to": target}
        if source != "auto":
            params["from"] = source
        headers = {
            "Ocp-Apim-Subscription-Key": key,
            "Ocp-Apim-Subscription-Region": region,
            "Content-Type": "application/json"
        }
        body = [{"Text": text}]
        r = requests.post(base, params=params, headers=headers, json=body, timeout=15)
        r.raise_for_status()
        data = r.json()
        return data[0]["translations"][0]["text"]
    except requests.exceptions.RequestException as re:
        try:
            body = re.response.text if hasattr(re, "response") and re.response is not None else str(re)
        except Exception:
            body = str(re)
        return "__ERROR__:" + str(re) + " | resp: " + str(body)
    except Exception as e:
        return "__ERROR__:" + str(e)

def translate_with_fallback_py(text, source, target):
    try:
        src = None if source == "auto" else source
        return DeepGoogleTranslator(source=src or 'auto', target=target).translate(text)
    except Exception as e:
        # deterministic small mock fallback
        return f"[MOCK {source}->{target}] " + " ".join(reversed(text.split()))

# Register both callbacks
colab_output.register_callback("translation.azure", translate_with_azure_py)
colab_output.register_callback("translation.fallback", translate_with_fallback_py)
print("Registered callbacks: 'translation.azure' and 'translation.fallback'.")

"""**Step 5:** Inject the HTML UI that tries Azure first and falls back automatically"""

from IPython.display import HTML, display
html_ui = """
<div style="font-family: Roboto, Arial, sans-serif; max-width:900px; border:1px solid #ddd; padding:12px; border-radius:8px;">
  <h3 style="margin-top:0">Translation UI — Azure (auto-fallback)</h3>
  <div style="display:flex; gap:8px; margin-bottom:8px; align-items:center;">
    <label style="min-width:90px;">Source:</label>
    <select id="src" style="flex:1; padding:6px;">
      <option value="auto">Auto Detect (auto)</option>
      <option value="en">English (en)</option>
      <option value="es">Spanish (es)</option>
      <option value="fr">French (fr)</option>
      <option value="de">German (de)</option>
      <option value="hi">Hindi (hi)</option>
    </select>
    <label style="min-width:70px; margin-left:8px;">Target:</label>
    <select id="tgt" style="width:170px; padding:6px;">
      <option value="en">English (en)</option>
      <option value="es">Spanish (es)</option>
      <option value="fr">French (fr)</option>
      <option value="de">German (de)</option>
      <option value="hi">Hindi (hi)</option>
    </select>
  </div>

  <div style="margin-bottom:8px;">
    <label style="display:block; font-weight:600; margin-bottom:4px;">Input Text</label>
    <textarea id="inputTxt" rows="5" style="width:100%; padding:8px; font-size:14px;">Hello, how are you?</textarea>
  </div>

  <div style="display:flex; gap:8px; margin-bottom:8px;">
    <button id="translateBtn" style="padding:8px 14px; background:#1f6feb; color:white; border:none; border-radius:6px; cursor:pointer;">Translate</button>
    <button id="clearBtn" style="padding:8px 14px; border:1px solid #bbb; border-radius:6px; cursor:pointer;">Clear</button>
    <button id="copyBtn" style="padding:8px 14px; border:1px solid #bbb; border-radius:6px; cursor:pointer;">Copy</button>
    <button id="speakBtn" style="padding:8px 14px; border:1px solid #bbb; border-radius:6px; cursor:pointer;">Speak</button>
    <div id="status" style="margin-left:12px; align-self:center; color:#333;"></div>
  </div>

  <div>
    <label style="display:block; font-weight:600; margin-bottom:4px;">Translated Text</label>
    <textarea id="outputTxt" rows="6" style="width:100%; padding:8px; font-size:14px;" readonly></textarea>
  </div>

  <div style="margin-top:8px; font-size:12px; color:#666;">
    <div><strong>Debug (raw):</strong></div>
    <pre id="rawResp" style="background:#f8f8f8; padding:8px; border-radius:4px; max-height:160px; overflow:auto;"></pre>
  </div>
</div>

<script>
const statusEl = document.getElementById('status');
const rawEl = document.getElementById('rawResp');
function setStatus(msg, color='black'){ statusEl.innerText = msg; statusEl.style.color = color; }

// Try Azure first; if Azure returns an error indicating missing keys or other issues, fallback to `translation.fallback`
async function tryAzureThenFallback(text, src, tgt){
  try {
    // Attempt Azure call
    const az = await google.colab.kernel.invokeFunction('translation.azure', [text, src, tgt], {});
    rawEl.textContent = JSON.stringify(az, null, 2);
    // Find a usable string in the response
    function findString(obj){
      if(!obj) return null;
      if(typeof obj === 'string') return obj;
      if(Array.isArray(obj) && obj.length>0) return findString(obj[0]);
      if(typeof obj === 'object'){
        if('translated' in obj && typeof obj.translated === 'string') return obj.translated;
        for(const k of Object.keys(obj)){
          const r = findString(obj[k]); if(r) return r;
        }
      }
      return null;
    }
    let azExtract = findString(az);
    if (typeof azExtract === 'string' && azExtract.startsWith("__ERROR__:")) {
      // Azure specifically returned an error; fallback
      console.warn("Azure returned error, falling back:", azExtract);
      setStatus("Azure error — falling back to offline translator", "orange");
      // call fallback
      const fb = await google.colab.kernel.invokeFunction('translation.fallback', [text, src, tgt], {});
      rawEl.textContent = rawEl.textContent + "\\n\\nFallback raw:\\n" + JSON.stringify(fb, null, 2);
      const fbStr = findString(fb) || fb;
      return fbStr;
    }
    // If Azure returned a useful string, use it
    if (azExtract) return azExtract;
    // Nothing useful from Azure — attempt fallback
    const fb2 = await google.colab.kernel.invokeFunction('translation.fallback', [text, src, tgt], {});
    rawEl.textContent = rawEl.textContent + "\\n\\nFallback raw:\\n" + JSON.stringify(fb2, null, 2);
    return findString(fb2) || fb2;
  } catch(err){
    // If the invokeFunction itself fails (network / permission), fallback
    console.error("Invoke error, falling back:", err);
    setStatus("Invoke error — using fallback", "orange");
    try {
      const fb = await google.colab.kernel.invokeFunction('translation.fallback', [text, src, tgt], {});
      rawEl.textContent = "Invoke error raw:\\n" + String(err) + "\\n\\nFallback raw:\\n" + JSON.stringify(fb, null, 2);
      return findString(fb) || fb;
    } catch(e){
      rawEl.textContent = "Invoke error and fallback failed:\\n" + String(e);
      return "__ERROR__:Invoke and fallback both failed: " + String(e);
    }
  }
}

document.getElementById('translateBtn').onclick = async () => {
  const text = document.getElementById('inputTxt').value || '';
  const src = document.getElementById('src').value;
  const tgt = document.getElementById('tgt').value;
  if(!text.trim()){ setStatus('Enter text', 'red'); return; }
  setStatus('Translating...', 'black');
  document.getElementById('outputTxt').value = '';
  rawEl.textContent = '...waiting for Python callback...';
  const result = await tryAzureThenFallback(text, src, tgt);
  if (typeof result === 'string' && result.startsWith("__ERROR__:")) {
    setStatus(result.replace("__ERROR__:", ""), 'red');
    document.getElementById('outputTxt').value = '';
  } else {
    document.getElementById('outputTxt').value = result || '';
    setStatus('Translation complete', 'green');
  }
};

document.getElementById('clearBtn').onclick = () => {
  document.getElementById('inputTxt').value = '';
  document.getElementById('outputTxt').value = '';
  rawEl.textContent = '';
  setStatus('Cleared', 'black');
};

document.getElementById('copyBtn').onclick = async () => {
  const txt = document.getElementById('outputTxt').value || '';
  if(!txt){ setStatus('Nothing to copy', 'red'); return; }
  try { await navigator.clipboard.writeText(txt); setStatus('Copied', 'green'); }
  catch(e){ setStatus('Copy failed (allow clipboard)', 'red'); }
};

document.getElementById('speakBtn').onclick = () => {
  const txt = document.getElementById('outputTxt').value || '';
  if(!txt){ setStatus('Nothing to speak', 'red'); return; }
  try {
    const u = new SpeechSynthesisUtterance(txt);
    u.lang = document.getElementById('tgt').value || 'en';
    window.speechSynthesis.cancel();
    window.speechSynthesis.speak(u);
    setStatus('Speaking...', 'black');
  } catch(e){ setStatus('TTS not supported', 'red'); }
};
</script>
"""
display(HTML(html_ui))
print("Azure-enabled UI injected. If Azure keys are present, the UI will use Azure; otherwise it falls back automatically.")

"""**Step 6:** Safe programmatic test (direct Python calls)"""

import time, traceback, os

print("Running safe programmatic tests (direct Python calls) for Azure and fallback...")

# Ensure callbacks / functions exist; if they don't, instruct how to re-run registration cell
need_reregister = False
for fname in ("translate_with_azure_py", "translate_with_fallback_py"):
    if fname not in globals():
        print(f"WARNING: function '{fname}' is not defined in this kernel. Re-run Cell 6 to register callbacks.")
        need_reregister = True

if need_reregister:
    raise RuntimeError("Required translation functions are missing. Re-run the cell that registers callbacks (Cell 6) and try again.")

# Test values
text = "Hello, how are you?"
src = "en"
tgt = "de"

# 1) Direct Azure call (fast; times out only if requests blocks)
try:
    print("\n--- Azure direct call (Python) ---")
    start = time.time()
    az_res = translate_with_azure_py(text, src, tgt)
    elapsed = time.time() - start
    print(f"Elapsed: {elapsed:.3f}s")
    print("Azure raw result repr:", repr(az_res))
    if isinstance(az_res, str) and az_res.startswith("__ERROR__:"):
        print("Azure reported error:", az_res.replace("__ERROR__:", ""))
    else:
        print("Azure translation:", az_res)
except Exception:
    print("Azure call raised exception:")
    traceback.print_exc()

# 2) Direct fallback call
try:
    print("\n--- Fallback direct call (Python) ---")
    start = time.time()
    fb_res = translate_with_fallback_py(text, src, tgt)
    elapsed = time.time() - start
    print(f"Elapsed: {elapsed:.3f}s")
    print("Fallback raw result repr:", repr(fb_res))
    print("Fallback translation:", fb_res)
except Exception:
    print("Fallback call raised exception:")
    traceback.print_exc()

print("\nDone. These direct calls do not use the browser JS bridge and will not hang waiting on promises.")

