# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LK_W9EXsGJ_yWne409FhtKqEF4DCROHF

# FAQ Chatbot (cleaned)
This notebook:
1. Loads a small FAQ dataset.
2. Preprocesses text with spaCy.
3. Builds a TF-IDF + cosine similarity matcher.
4. Provides a simple inline chat UI (ipywidgets) for testing.

**Step 1:** Install dependencies (Colab)
"""

!python -m pip install --upgrade pip setuptools wheel
!pip install -q spacy==3.8.0 scikit-learn==1.4.2 pandas==2.2.2 joblib==1.3.2
!python -m spacy download en_core_web_sm

"""**Step 2:** Imports & quick sanity check (versions)"""

import sys
import importlib

packages = ["spacy","sklearn","pandas","numpy","joblib"]
print("Python:", sys.version.replace("\n"," "))

for p in packages:
    try:
        m = importlib.import_module(p)
        print(f"{p}: OK, version:", getattr(m, "__version__", "unknown"))
    except Exception as e:
        print(f"{p}: IMPORT ERROR -> {e.__class__.__name__}: {e}")

"""**Step 3:** Create example faqs.csv (from original file)"""

csv_text = """question,answer
How long does the battery last on a single charge?,"Typical battery life is up to 20 hours of music playback depending on volume and usage."
How do I pair the headphones with my phone?,"Turn on pairing mode (press and hold the power button for 5 seconds), enable Bluetooth on your phone, and select the device from the Bluetooth list."
Can the headphones be used while charging?,"Some models support pass-through audio while charging; check your product manual. Generally it's safe but depends on the model."
Do the headphones support noise cancellation?,"Yes — the model supports active noise cancellation (ANC). You can toggle ANC in the headphone controls or companion app."
What is the warranty period?,"The product includes a 12-month limited warranty covering manufacturing defects (terms & conditions apply)."
How do I reset the headphones?,"To reset: power off, then press and hold power + volume up for 10 seconds until the LED flashes."
What Bluetooth versions are supported?,"This model supports Bluetooth 5.2 for improved range and stability."
"""
with open("faqs.csv","w", encoding="utf-8") as f:
    f.write(csv_text)

import pandas as pd
display(pd.read_csv("faqs.csv"))

"""**Step 4:** Imports for NLP, vectorization and UI (single cell)"""

import spacy
import numpy as np
import pandas as pd

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# ipywidgets UI (as in original file)
import ipywidgets as widgets
from IPython.display import display, HTML

"""**Step 5:** Load spaCy model & preprocess function"""

# load spaCy model (exclude ner to speed up)
nlp = spacy.load("en_core_web_sm", exclude=["ner"])

def preprocess_text(text, min_token_length=2):
    doc = nlp(str(text).lower())
    tokens = []
    for token in doc:
        if token.is_alpha and not token.is_stop:
            lemma = token.lemma_.strip()
            if len(lemma) >= min_token_length:
                tokens.append(lemma)
    return " ".join(tokens)

# quick sanity check
print(preprocess_text("How do I pair the headphones with my phone?"))

"""**Step 6:** Build TF-IDF matrix from FAQs"""

# load FAQs
df = pd.read_csv("faqs.csv")
df["question_proc"] = df["question"].astype(str).apply(preprocess_text)

# vectorizer (keeps default tokenization but original used a relaxed token pattern)
vectorizer = TfidfVectorizer(analyzer="word", token_pattern=r"(?u)\b\w+\b")
tfidf_matrix = vectorizer.fit_transform(df["question_proc"])

print("FAQ count:", len(df))
print("TF-IDF shape:", tfidf_matrix.shape)
df[["question","question_proc"]]

"""**Step 7:** Matching function: get_best_faq_answer"""

def get_best_faq_answer(user_question, threshold=0.25):
    user_proc = preprocess_text(user_question)
    if not user_proc.strip():
        return {"answer":"Sorry — I couldn't understand that. Could you rephrase?",
                "matched_question":None,"score":0.0,"index":None}
    user_vec = vectorizer.transform([user_proc])
    sims = cosine_similarity(user_vec, tfidf_matrix).flatten()
    best_idx = int(np.argmax(sims))
    best_score = float(sims[best_idx])
    if best_score >= threshold:
        return {"answer": df.loc[best_idx,"answer"],
                "matched_question": df.loc[best_idx,"question"],
                "score": best_score,"index": best_idx}
    else:
        return {"answer": f"I couldn't find a confident match. Closest FAQ: \"{df.loc[best_idx,'question']}\" — Answer: {df.loc[best_idx,'answer']}",
                "matched_question": df.loc[best_idx,"question"],
                "score": best_score,"index": best_idx}

"""**Step 8:** Quick tests (console)"""

tests = ["How do I connect to Bluetooth?", "Does it have ANC?", "How to reset?", "What's the battery life?"]
for t in tests:
    res = get_best_faq_answer(t)
    print(f"Q: {t}\n -> matched: {res['matched_question']} (score={res['score']:.3f})\n -> answer: {res['answer']}\n")

"""**Step 9:** Inline chat UI using ipywidgets"""

# UI widgets
chat_output = widgets.HTML(value="", placeholder="", description="")
text_input = widgets.Text(placeholder="Type your question and press Enter...", continuous_update=False)
send_btn = widgets.Button(description="Send", button_style="primary")
clear_btn = widgets.Button(description="Clear", button_style="warning")

_history_html = ""

def append_message(role, message):
    global _history_html
    role = role.lower()
    if role == "user":
        block = f'''
        <div style="display:flex; margin:6px 0;">
          <div style="min-width:70px; font-weight:600; color:#0b57d0">User:</div>
          <div style="flex:1; background:#e8f0ff; padding:8px 10px; border-radius:8px;">{message}</div>
        </div>
        '''
    else:
        block = f'''
        <div style="display:flex; margin:6px 0;">
          <div style="min-width:70px; font-weight:600; color:#056608">Bot:</div>
          <div style="flex:1; background:#f1fff0; padding:8px 10px; border-radius:8px;">{message}</div>
        </div>
        '''
    _history_html += block
    chat_output.value = f'<div style="max-height:400px; overflow:auto; padding:6px; border:1px solid #ddd; border-radius:6px; background:#fff">{_history_html}</div>'

def on_send(_=None):
    user_text = text_input.value.strip()
    if not user_text:
        return
    append_message("user", user_text)
    text_input.value = ""
    try:
        res = get_best_faq_answer(user_text, threshold=0.25)
        ans = res.get("answer", "Sorry — error getting answer.")
        score = res.get("score", None)
        if score is not None:
            ans = f"{ans}<div style='margin-top:6px; font-size:0.9em; color:#666'><em> (match score: {score:.3f})</em></div>"
    except Exception as e:
        ans = f"Error running matcher: {e}"
    append_message("bot", ans)

def on_clear(_=None):
    global _history_html
    _history_html = ""
    chat_output.value = ""

send_btn.on_click(on_send)
clear_btn.on_click(on_clear)
text_input.on_submit(lambda x: on_send())

controls = widgets.HBox([text_input, send_btn, clear_btn], layout=widgets.Layout(margin="8px 0"))
title = widgets.HTML("<h3 style='margin:0 0 8px 0'>FAQ Chatbot — Inline UI (ipywidgets)</h3>")
display(widgets.VBox([title, chat_output, controls]))

# focus the text field (works in many browsers)
try:
    display(HTML("<script>document.querySelector('input[placeholder]').focus();</script>"))
except Exception:
    pass

